### ISSUE TITLE
"Information" Widget won't load

### ISSUE THREAD

**Issue by poundifdef** [poundifdef/VirginMobileMinutesChecker#12]
When I add the "Information" widget (not the pie graph) I get a "Problem Loading Widget" message and this stacktrace:

```
07-04 11:13:26.957: WARN/AppWidgetHostView(2177): updateAppWidget couldn't find any view, using error view
07-04 11:13:26.957: WARN/AppWidgetHostView(2177): android.widget.RemoteViews$ActionException: can't find view: 0x7f080025
07-04 11:13:26.957: WARN/AppWidgetHostView(2177):     at android.widget.RemoteViews$ReflectionAction.apply(RemoteViews.java:446)
07-04 11:13:26.957: WARN/AppWidgetHostView(2177):     at android.widget.RemoteViews.performApply(RemoteViews.java:955)
07-04 11:13:26.957: WARN/AppWidgetHostView(2177):     at android.widget.RemoteViews.apply(RemoteViews.java:932)
07-04 11:13:26.957: WARN/AppWidgetHostView(2177):     at android.appwidget.AppWidgetHostView.updateAppWidget(AppWidgetHostView.java:219)
07-04 11:13:26.957: WARN/AppWidgetHostView(2177):     at android.appwidget.AppWidgetHostView.updateAppWidget(AppWidgetHostView.java:155)
07-04 11:13:26.957: WARN/AppWidgetHostView(2177):     at android.appwidget.AppWidgetHost.createView(AppWidgetHost.java:218)
07-04 11:13:26.957: WARN/AppWidgetHostView(2177):     at com.android.launcher2.Launcher.completeAddAppWidget(Launcher.java:946)
07-04 11:13:26.957: WARN/AppWidgetHostView(2177):     at com.android.launcher2.Launcher.onActivityResult(Launcher.java:564)
07-04 11:13:26.957: WARN/AppWidgetHostView(2177):     at com.android.launcher2.Launcher.addAppWidget(Launcher.java:1226)
07-04 11:13:26.957: WARN/AppWidgetHostView(2177):     at com.android.launcher2.Launcher.onActivityResult(Launcher.java:561)
07-04 11:13:26.957: WARN/AppWidgetHostView(2177):     at android.app.Activity.dispatchActivityResult(Activity.java:3890)
07-04 11:13:26.957: WARN/AppWidgetHostView(2177):     at android.app.ActivityThread.deliverResults(ActivityThread.java:3511)
07-04 11:13:26.957: WARN/AppWidgetHostView(2177):     at android.app.ActivityThread.handleSendResult(ActivityThread.java:3557)
07-04 11:13:26.957: WARN/AppWidgetHostView(2177):     at android.app.ActivityThread.access$2800(ActivityThread.java:125)
07-04 11:13:26.957: WARN/AppWidgetHostView(2177):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2063)
07-04 11:13:26.957: WARN/AppWidgetHostView(2177):     at android.os.Handler.dispatchMessage(Handler.java:99)
07-04 11:13:26.957: WARN/AppWidgetHostView(2177):     at android.os.Looper.loop(Looper.java:123)
07-04 11:13:26.957: WARN/AppWidgetHostView(2177):     at android.app.ActivityThread.main(ActivityThread.java:4627)
07-04 11:13:26.957: WARN/AppWidgetHostView(2177):     at java.lang.reflect.Method.invokeNative(Native Method)
07-04 11:13:26.957: WARN/AppWidgetHostView(2177):     at java.lang.reflect.Method.invoke(Method.java:521)
07-04 11:13:26.957: WARN/AppWidgetHostView(2177):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:858)
07-04 11:13:26.957: WARN/AppWidgetHostView(2177):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
07-04 11:13:26.957: WARN/AppWidgetHostView(2177):     at dalvik.system.NativeStart.main(Native Method)
07-04 11:13:27.002: WARN/AppWidgetHostView(2177): updateAppWidget couldn't find any view, using error view
07-04 11:13:27.002: WARN/AppWidgetHostView(2177): android.widget.RemoteViews$ActionException: can't find view: 0x7f080025
07-04 11:13:27.002: WARN/AppWidgetHostView(2177):     at android.widget.RemoteViews$ReflectionAction.apply(RemoteViews.java:446)
07-04 11:13:27.002: WARN/AppWidgetHostView(2177):     at android.widget.RemoteViews.performApply(RemoteViews.java:955)
07-04 11:13:27.002: WARN/AppWidgetHostView(2177):     at android.widget.RemoteViews.apply(RemoteViews.java:932)
07-04 11:13:27.002: WARN/AppWidgetHostView(2177):     at android.appwidget.AppWidgetHostView.updateAppWidget(AppWidgetHostView.java:219)
07-04 11:13:27.002: WARN/AppWidgetHostView(2177):     at android.appwidget.AppWidgetHost.updateAppWidgetView(AppWidgetHost.java:250)
07-04 11:13:27.002: WARN/AppWidgetHostView(2177):     at android.appwidget.AppWidgetHost.startListening(AppWidgetHost.java:122)
07-04 11:13:27.002: WARN/AppWidgetHostView(2177):     at com.android.launcher2.Launcher.onResume(Launcher.java:584)
07-04 11:13:27.002: WARN/AppWidgetHostView(2177):     at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1149)
07-04 11:13:27.002: WARN/AppWidgetHostView(2177):     at android.app.Activity.performResume(Activity.java:3823)
07-04 11:13:27.002: WARN/AppWidgetHostView(2177):     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3118)
07-04 11:13:27.002: WARN/AppWidgetHostView(2177):     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3143)
07-04 11:13:27.002: WARN/AppWidgetHostView(2177):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2059)
07-04 11:13:27.002: WARN/AppWidgetHostView(2177):     at android.os.Handler.dispatchMessage(Handler.java:99)
07-04 11:13:27.002: WARN/AppWidgetHostView(2177):     at android.os.Looper.loop(Looper.java:123)
07-04 11:13:27.002: WARN/AppWidgetHostView(2177):     at android.app.ActivityThread.main(ActivityThread.java:4627)
07-04 11:13:27.002: WARN/AppWidgetHostView(2177):     at java.lang.reflect.Method.invokeNative(Native Method)
07-04 11:13:27.002: WARN/AppWidgetHostView(2177):     at java.lang.reflect.Method.invoke(Method.java:521)
07-04 11:13:27.002: WARN/AppWidgetHostView(2177):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:858)
07-04 11:13:27.002: WARN/AppWidgetHostView(2177):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
07-04 11:13:27.002: WARN/AppWidgetHostView(2177):     at dalvik.system.NativeStart.main(Native Method)
07-04 11:13:27.012: WARN/InputManagerService(2084): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@438835a0
```

**Comment by poundifdef** [comment]
Oops. Looks like I just needed to do an `ant clean` and then `ant install`.
